version: "3"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: template-database
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:

networks:
  template:
    driver: bridge
